require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Mobiauto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pre_install do |installer|
  # workaround for CocoaPods/CocoaPods#3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end
  
  target 'MobiautoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobiautoUITests' do
    # Pods for testing
  end

end
