require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Mobiauto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Pods for Mobiauto

  target 'MobiautoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobiautoUITests' do
    # Pods for testing
  end

end
